# Generated by Django 4.2.13 on 2024-05-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0003_alter_rasp_idaud_alter_rasp_idgrp_alter_rasp_idpara_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='para',
            options={'ordering': ['num'], 'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
    ]
