# Generated by Django 4.2.13 on 2024-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('para', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
    ]
