# Generated by Django 4.2.13 on 2024-05-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0004_alter_para_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasp',
            name='dt',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
