# Generated by Django 4.2.13 on 2024-06-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30, verbose_name='Номер')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MyGrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='grpany', to='grp.grp', verbose_name='Группа')),
                ('myid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='grpme', to='person.person', verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Списки групп',
                'ordering': ['id'],
                'unique_together': {('myid', 'grpid')},
            },
        ),
    ]
