# Generated by Django 4.2.13 on 2024-06-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predmet', '0001_initial'),
        ('grpp', '0001_initial'),
        ('aud', '0001_initial'),
        ('person', '0001_initial'),
        ('para', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(null=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('idmaster', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='idmaster', to='person.person', verbose_name='Хозяин')),
                ('idpara', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='para.para', verbose_name='Пара')),
                ('idpers', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='iddest', to='person.person', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Резерв',
                'verbose_name_plural': 'Резерв',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rasp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(null=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('idaud', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aud.aud', verbose_name='Аудитория')),
                ('idgrp', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='grpp.grp', verbose_name='Группа')),
                ('idpara', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='para.para', verbose_name='Пара')),
                ('idpers', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='person.person', verbose_name='Преподаватель')),
                ('idpredmet', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='predmet.predmet', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rasp',
            constraint=models.UniqueConstraint(fields=('dt', 'idpara', 'idgrp'), name='cidgrp'),
        ),
        migrations.AddConstraint(
            model_name='rasp',
            constraint=models.UniqueConstraint(fields=('dt', 'idpara', 'idaud'), name='cidaud'),
        ),
        migrations.AddConstraint(
            model_name='rasp',
            constraint=models.UniqueConstraint(fields=('dt', 'idpara', 'idpers'), name='cidpers'),
        ),
    ]
