# Generated by Django 4.2.13 on 2024-05-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('descr', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30, verbose_name='Номер')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('fam', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('otch', models.CharField(max_length=100, verbose_name='Отчество')),
                ('born', models.IntegerField(verbose_name='Год. рожд.')),
                ('dolg', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rasp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(null=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('idaud', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rasp.aud', verbose_name='Аудитория')),
                ('idgrp', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rasp.grp', verbose_name='Группа')),
                ('idpara', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rasp.para', verbose_name='Пара')),
                ('idpers', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rasp.person', verbose_name='Преподаватель')),
                ('idpredmet', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rasp.predmet', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['id'],
            },
        ),
    ]
