# Generated by Django 4.2.13 on 2024-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rasp',
            unique_together={('dt', 'idpara', 'idpredmet')},
        ),
    ]
