# Generated by Django 4.2.13 on 2024-06-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='1111', max_length=100, verbose_name='Пароль'),
        ),
    ]
