# Generated by Django 4.2.13 on 2024-06-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_mynote'),
        ('rasp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XlsRaspPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nk', models.IntegerField(blank=True, null=True, verbose_name='Номер колонки')),
                ('nd', models.IntegerField(blank=True, null=True, verbose_name='Номер дня')),
                ('np', models.IntegerField(blank=True, null=True, verbose_name='Номер занятия')),
                ('xls', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ячейка А1')),
                ('dop1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп1')),
                ('dop2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп2')),
                ('xlsrow', models.IntegerField(blank=True, null=True, verbose_name='Строка')),
                ('xlscol', models.IntegerField(blank=True, null=True, verbose_name='Столбец')),
                ('idpers', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='idxlsrasppers', to='person.person', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Бланк',
                'verbose_name_plural': 'Бланки',
                'ordering': ['id'],
            },
        ),
    ]
