# Generated by Django 4.2.13 on 2024-05-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0002_alter_rasp_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rasp',
            unique_together={('dt', 'idpara', 'idgrp')},
        ),
    ]
