# Generated by Django 5.0.6 on 2024-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0002_rasp_dt_rasp_dw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasp',
            name='dw',
            field=models.IntegerField(default=0, verbose_name='День недели'),
        ),
    ]
