# Generated by Django 4.2.13 on 2024-06-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0003_alter_rasp_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rasp',
            unique_together={('dt', 'idpara', 'idpers')},
        ),
    ]
