# Generated by Django 4.2.13 on 2024-06-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_isadmin'),
        ('rasp', '0003_reserv'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='idmaster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='idmaster', to='person.person', verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='idpers',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='iddest', to='person.person', verbose_name='Преподаватель'),
        ),
    ]
