# Generated by Django 5.0.6 on 2024-05-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0003_alter_rasp_dw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasp',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='rasp',
            name='dw',
        ),
    ]
