# Generated by Django 4.2.13 on 2024-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0004_alter_rasp_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rasp',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rasp',
            constraint=models.UniqueConstraint(fields=('dt', 'idpara', 'idgrp'), name='cidgrp'),
        ),
        migrations.AddConstraint(
            model_name='rasp',
            constraint=models.UniqueConstraint(fields=('dt', 'idpara', 'idaud'), name='cidaud'),
        ),
        migrations.AddConstraint(
            model_name='rasp',
            constraint=models.UniqueConstraint(fields=('dt', 'idpara', 'idpers'), name='cidpers'),
        ),
    ]
