# Generated by Django 4.2.13 on 2024-06-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0005_alter_rasp_unique_together_rasp_cidgrp_rasp_cidaud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год. рожд.'),
        ),
    ]
