# Generated by Django 4.2.13 on 2024-06-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0007_mess'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='fromid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='frompers', to='rasp.person', verbose_name='От кого'),
        ),
        migrations.AddField(
            model_name='mess',
            name='toid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='topers', to='rasp.person', verbose_name='Кому'),
        ),
    ]
