# Generated by Django 4.2.13 on 2024-06-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0008_mess_fromid_mess_toid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='mypers', to='rasp.person', verbose_name='Хозяин')),
                ('persid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='anypers', to='rasp.person', verbose_name='Персона')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
                'ordering': ['id'],
                'unique_together': {('myid', 'persid')},
            },
        ),
    ]
