# Generated by Django 4.2.13 on 2024-06-03 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0009_mypers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
