# Generated by Django 4.2.13 on 2024-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0010_alter_mess_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='warn',
            field=models.CharField(choices=[('0', 'ОБЫЧНОЕ'), ('1', 'ВАЖНОЕ')], default=0, max_length=1),
        ),
    ]
