# Generated by Django 4.2.13 on 2024-06-04 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rasp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('short', models.CharField(max_length=100, verbose_name='Кратко')),
                ('long', models.CharField(max_length=255, verbose_name='Полно')),
                ('isActive', models.IntegerField(default=1, verbose_name='Активно')),
                ('warn', models.CharField(choices=[('0', 'ОБЫЧНОЕ'), ('1', 'ВАЖНОЕ')], default=0, max_length=1)),
                ('fromid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='frompers', to='rasp.person', verbose_name='От кого')),
                ('toid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='topers', to='rasp.person', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['id'],
            },
        ),
    ]
