# Generated by Django 4.2.13 on 2024-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aud',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
