# Generated by Django 5.0.6 on 2024-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aud',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterField(
            model_name='aud',
            name='descr',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aud',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
