# Generated by Django 4.2.13 on 2024-06-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('fam', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('otch', models.CharField(max_length=100, verbose_name='Отчество')),
                ('born', models.IntegerField(blank=True, null=True, verbose_name='Год. рожд.')),
                ('dolg', models.CharField(max_length=100, verbose_name='Должность')),
                ('password', models.CharField(default='1111', max_length=100, verbose_name='Пароль')),
                ('isAdmin', models.IntegerField(blank=True, default='0', verbose_name='Админ')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='MyPers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='persme', to='person.person', verbose_name='Хозяин')),
                ('persid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='persany', to='person.person', verbose_name='Персона')),
            ],
            options={
                'verbose_name': 'Список преподавателей',
                'verbose_name_plural': 'Списки преподавателей',
                'ordering': ['id'],
                'unique_together': {('myid', 'persid')},
            },
        ),
    ]
