# Generated by Django 4.2.13 on 2024-06-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profphoto',
            field=models.ImageField(blank=True, default='dolly.png', upload_to='avatars', verbose_name='Фото'),
        ),
    ]
