# Generated by Django 5.0.6 on 2024-05-16 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rasp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.IntegerField(verbose_name='Год. рожд.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dolg',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fam',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='otch',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='rasp',
            name='idpers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='rasp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
