# Generated by Django 4.2.13 on 2024-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_profphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profphoto',
            field=models.ImageField(blank=True, default='avatars/dolly.png', upload_to='avatars', verbose_name='Фото'),
        ),
    ]
