# Generated by Django 5.0.6 on 2024-05-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_options_alter_person_born_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasp',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
