# Generated by Django 5.0.6 on 2024-05-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_rasp_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rasp',
        ),
    ]
